
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT_SUCCESS'

export const QUESTION_GET_ALL_SUCCESS = 'QUESTION_GET_ALL_SUCCESS'
export const QUESTION_GET_ONE_SUCCESS = 'QUESTION_GET_ONE_SUCCESS'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_TOGGLEVOTE_SUCCESS = 'QUESTION_TOGGLEVOTE_SUCCESS'
export const QUESTION_ANSWER_CREATE_SUCCESS = 'QUESTION_ANSWER_CREATE_SUCCESS'
export const QUESTION_ANSWER_TOGGLEVOTE_SUCCESS = 'QUESTION_ANSWER_TOGGLEVOTE_SUCCESS'
export const QUESTION_ANSWER_DELETE_SUCCESS = 'QUESTION_ANSWER_DELETE_SUCCESS'

export const NOTIFY_INFO = 'NOTIFY_INFO'
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS'
export const NOTIFY_ERROR = 'NOTIFY_ERROR'
export const NOTIFY_WARNING = 'NOTIFY_WARNING'
